"use strict";
// Test class Point
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(-10, -5);
var point1 = new point_1.Point(1, 2);
var point2 = new point_1.Point(-2, 50);
var point3 = new point_1.Point(-20, 5);
var point4 = new point_1.Point(-15, 50);
var points = [point4, point2, point3, point1];
console.log(myPoint.getX());
console.log(myPoint.getY());
myPoint.setX(-5);
myPoint.setY(25);
console.log(myPoint.getX());
console.log(myPoint.getY());
console.log(myPoint.distanceToOrigin());
console.log(myPoint.calculateDistance(point1));
console.log(myPoint.calculateQuadrant());
console.log(myPoint.calculateNearest(points));
